# Generated by Django 3.1.3 on 2020-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='ok',
            field=models.IntegerField(default=0),
        ),
    ]
