# Generated by Django 3.1.3 on 2020-11-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0002_notificationtype_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='ok',
        ),
    ]
