# Generated by Django 3.1.3 on 2020-11-12 22:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0003_remove_notificationtype_ok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETFAndReversePairRobot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='TradeDataHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=10)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name=django.utils.timezone.now)),
                ('buy_price', models.FloatField(default=0.0)),
                ('buy_order_client_id', models.CharField(default='', max_length=40)),
                ('sell_order_client_id', models.CharField(blank=True, max_length=40, null=True)),
                ('sell_price', models.FloatField(blank=True, null=True)),
                ('sell_date', models.DateTimeField(blank=True, null=True, verbose_name=django.utils.timezone.now)),
                ('winning_order_client_id', models.CharField(blank=True, max_length=40, null=True)),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.etfandreversepairrobot')),
            ],
        ),
    ]
