# Generated by Django 3.1.3 on 2020-11-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0004_etfandreversepairrobot_tradedataholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedataholder',
            name='buy_order_client_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tradedataholder',
            name='sell_order_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradedataholder',
            name='winning_order_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
