# Generated by Django 3.1.3 on 2020-11-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0005_auto_20201112_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='aalue',
            field=models.IntegerField(default=0),
        ),
    ]
