# Generated by Django 3.1.3 on 2020-11-13 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0006_notificationtype_aalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='BullBearETFData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('bull_price', models.FloatField(default=0)),
                ('bear_price', models.FloatField(default=0)),
                ('etf_price', models.FloatField(default=0)),
                ('bull_symbol', models.CharField(default='', max_length=10)),
                ('bear_symbol', models.CharField(default='', max_length=10)),
                ('etf_symbol', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RobotEquitySymbols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('description', models.CharField(default='', max_length=100)),
                ('symbol', models.CharField(default='', max_length=6)),
                ('owners', models.CharField(default='', max_length=25)),
                ('leverage', models.CharField(default='', max_length=5)),
                ('bullishSymbol', models.CharField(default='', max_length=6)),
                ('bearishSymbol', models.CharField(default='', max_length=6)),
                ('top_15_stocks', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
