# Generated by Django 3.1.3 on 2020-11-13 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0007_bullbearetfdata_robotequitysymbols'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('zipcode', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=10)),
                ('geolocation', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('name', models.CharField(default='', max_length=25)),
                ('membership_status', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Trial', 'Trial')], default='Trial', max_length=10)),
                ('status_creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('billing_information', models.CharField(choices=[('Visa', 'Visa'), ('Mastercard', 'Mastercard'), ('Discover', 'Discover'), ('Paypal', 'Paypal')], default='Visa', max_length=10)),
                ('credit_card_number', models.CharField(default='', max_length=20)),
                ('address', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.address')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerageInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('website', models.CharField(default='', max_length=20)),
                ('connection_type', models.CharField(default='', max_length=20)),
                ('connection_API_Key', models.CharField(default='', max_length=20)),
                ('brokerage_type', models.CharField(choices=[('Local Account', 'Local Account'), ('eTrade Regular', 'eTrade Regular'), ('eTrade Retirement', 'eTrade Retirement'), ('Alpaca', 'Alpaca'), ('Ameritrade', 'Ameritrade')], default='Alpaca', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=50)),
                ('website', models.CharField(default='', max_length=40)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.address')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified_date', models.DateTimeField(auto_now_add=True, verbose_name='date modified')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('main_phone', models.CharField(default='', max_length=30)),
                ('alternate_phone', models.CharField(default='', max_length=30)),
                ('main_email', models.CharField(default='', max_length=30)),
                ('alternate_email', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('Principal', 'Principal'), ('Director', 'Director'), ('S', 'Student'), ('N/A', 'Not Available')], default='Investor', max_length=25)),
                ('short_bio', models.TextField(default=' ')),
                ('tax_bracket', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('password', models.CharField(default='', max_length=50)),
                ('recovery_phone', models.CharField(default='', max_length=30)),
                ('recovery_email', models.CharField(default='', max_length=30)),
                ('password_hint_1', models.CharField(default='', max_length=30)),
                ('password_hint_2', models.CharField(default='', max_length=30)),
                ('password_hint_3', models.CharField(default='', max_length=30)),
                ('enable_two_step', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquityTradingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=10)),
                ('trade_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('volume', models.FloatField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarketBusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('time_zone', models.CharField(choices=[('EST', 'EST'), ('EURO', 'EURO'), ('24_7', '24_7')], default='EST', max_length=10)),
                ('opening_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('closing_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='RobotVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=10)),
                ('major', models.IntegerField(blank=True, default=0)),
                ('minor', models.IntegerField(blank=True, default=0)),
                ('release', models.IntegerField(blank=True, default=0)),
                ('changes', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StartupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('comment', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('action', models.CharField(choices=[('start', 'start'), ('stop', 'stop')], default='start', max_length=10)),
                ('object_type', models.CharField(choices=[('start', 'start'), ('stop', 'stop')], default='start', max_length=10)),
                ('object_identifier', models.IntegerField(blank=True, default=0, null=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='basic_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customerbasic'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.billing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.businessinformation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='personal_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customerprofile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='security_information',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customersecurity'),
        ),
    ]
