# Generated by Django 3.1.3 on 2020-11-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0008_auto_20201113_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='cost_basis_per_roundtrip',
            field=models.CharField(choices=[('500', '500'), ('1,000', '1,000'), ('1,500', '1,500'), ('2,500', '2,500'), ('4,000', '4,000'), ('5,000', '5,000')], default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='data_source_choice',
            field=models.CharField(choices=[('live', 'live'), ('backtest', 'backtest'), ('paper', 'paper')], default='backtest', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='hold_time_includes_holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='internal_name',
            field=models.CharField(blank=True, default='egghead', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='liquidate_on_next_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='live_data_check_interval',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('5', '5'), ('10', '10')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='max_hold_time',
            field=models.CharField(choices=[('5', '5'), ('14', '14'), ('21', '21'), ('30', '30'), ('No Max', 'No Max')], default='5', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='max_roundtrips',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('10', '10'), ('12', '12')], default='10', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='max_sell_transactions_per_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('unlimited', 'unlimited')], default='unlimited', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='minimum_hold_time',
            field=models.CharField(choices=[('0', '0'), ('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customer'),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='profit_target_per_roundtrip',
            field=models.CharField(choices=[('.05', '.05'), ('.075', '.075'), ('.1', '.1'), ('.15', '.15')], default='.05', max_length=10),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='sell_remaining_before_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='symbols',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.robotequitysymbols'),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=150)),
                ('initial_cash_funds', models.FloatField(default=0)),
                ('current_cash_funds', models.FloatField(default=0)),
                ('max_robot_fraction', models.CharField(choices=[(0.1, '10%'), (0.2, '20%'), (0.25, '25%'), (0.3, '30%')], default='10', max_length=25)),
                ('cash_position_update_policy', models.CharField(choices=[(24, '1 day'), (1, 'hourly'), (0, 'immediate'), (48, '2 days'), (72, '3 days')], default='daily', max_length=15)),
                ('brokerage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.brokerageinformation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customer')),
            ],
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.portfolio'),
        ),
    ]
