# Generated by Django 3.1.3 on 2020-11-13 18:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0009_auto_20201113_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=150)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('strategy_class', models.CharField(choices=[('Bullish Bearish Pair', 'Bullish Bearish Pair'), ('Equity Bullish Bearish', 'Equity Bullish Bearish')], default='Bullish Bearish Pair', max_length=25)),
                ('strategy_category', models.CharField(choices=[('Babadjou', 'Babadjou'), ('Batcham', 'Batcham')], default='Babadjou', max_length=25)),
                ('visibility', models.BooleanField(default=True)),
                ('minimum_entries_before_trading', models.CharField(choices=[('2', '2'), ('4', '4'), ('6', '6')], default=2, max_length=25)),
                ('trade_only_after_fully_loaded', models.BooleanField(default=True)),
                ('manual_asset_composition_policy', models.BooleanField(default=True)),
                ('manual_asset_composition', models.CharField(choices=[('20-80', '20-80'), ('25-75', '25-75'), ('30-70', '30-70'), ('40-60', '40-60'), ('50-50', '50-50'), ('60-40', '60-40'), ('70-30', '70-30'), ('75-25', '75-25'), ('80-20', '80-20')], default='50-50', max_length=25)),
                ('automatic_generation_client_order_id', models.BooleanField(default=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.customerbasic')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProtectionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_asset_upon_acquisition', models.BooleanField(default=False)),
                ('protect_asset_upon_move_to_transition', models.BooleanField(default=False)),
                ('use_trailing_stops', models.BooleanField(default=False)),
                ('use_stop_market', models.BooleanField(default=False)),
                ('use_stop_limit', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.equitystrategy')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_force_buy_orders', models.CharField(choices=[('day', 'day'), ('gtc', 'gtc')], default='day', max_length=25)),
                ('time_in_force_sell_orders', models.CharField(choices=[('day', 'day'), ('gtc', 'gtc')], default='day', max_length=25)),
                ('acquisition_order_type', models.CharField(choices=[('market', 'market'), ('limit', 'limit')], default='market', max_length=25)),
                ('transition_order_type', models.CharField(choices=[('market', 'market'), ('limit', 'limit')], default='market', max_length=25)),
                ('completion_order_type', models.CharField(choices=[('market', 'market'), ('limit', 'limit')], default='market', max_length=25)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.equitystrategy')),
            ],
        ),
        migrations.CreateModel(
            name='DispositionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_transition_profit_policy', models.BooleanField(default=True)),
                ('in_transition_profit_target_ratio', models.CharField(choices=[(-0.25, '-.25'), (-0.15, '-.15'), (-0.1, '-.10'), (0.0, '0.0'), (0.1, '.10'), (0.15, '.15'), (0.25, '.25'), (0.35, '.35'), (0.45, '.45'), (0.5, '.50')], default='.10', max_length=25)),
                ('completion_profit_policy', models.BooleanField(default=True)),
                ('completion_complete_target_ratio', models.CharField(choices=[(0.4, '.40'), (0.5, '.50'), (0.75, '.75'), (1, '1'), (1.25, '1.25'), (1.5, '1.50'), (1.75, '1.75'), (2, '2'), (2.5, '2.50')], default='.40', max_length=25)),
                ('in_transition_asset_composition', models.CharField(choices=[('1Bull x 1Bear', '1Bull x 1Bear'), ('2Bull x 1Bear', '2Bull x 1Bear'), ('3Bull x 1Bear', '3Bull x 1Bear'), ('1Bull x 2Bear', '1Bull x 2Bear'), ('1Bull x 3Bear', '1Bull x 3Bear'), ('2Bull x 2Bear', '2Bull x 2Bear')], default='1Bull x 1Bear', max_length=25)),
                ('in_transition_strategy_type', models.CharField(choices=[('Asset Performance', 'Asset Performance'), ('Asset Acquisition Price', 'Asset Acquisition Price'), ('Price Based Inner Spread', 'Price Based Inner Spread'), ('Price Based Average Spread', 'Price Based Average Spread'), ('Price Based Average Spread 2', 'Price Based Average Spread 2')], default='Asset Performance', max_length=50)),
                ('in_transition_entry_strategy', models.CharField(choices=[('worstbull_and_worstbear', 'worstbull_and_worstbear'), ('bestbull_and_bestbear', 'bestbull_and_bestbear'), ('bestbull_and_worstbear', 'bestbull_and_worstbear'), ('worstbull_and_bestbear', 'worstbull_and_bestbear')], default='worstbull_and_worstbear', max_length=25)),
                ('in_transition_load_factor', models.CharField(choices=[('25', '25'), ('50', '50'), ('75', '75')], default='25', max_length=10)),
                ('completion_regression_policy', models.CharField(choices=[('NO Policy', 'NO Policy'), ('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=25)),
                ('completion_regression_duration', models.CharField(choices=[('-5', '-5'), ('-3', '-3'), ('-2', '-2'), ('-1', '-1')], default='-3', max_length=10)),
                ('completion_regression_factor', models.CharField(choices=[('20', '20'), ('25', '25'), ('33', '33')], default='25', max_length=10)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.equitystrategy')),
            ],
        ),
        migrations.CreateModel(
            name='AcquisitionPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_price_proximity', models.BooleanField(default=True)),
                ('number_or_percentage', models.CharField(choices=[('Stock Price by Number', 'Stock Price by Number'), ('Stock Price by Percentage', 'Stock Price by Percentage'), ('Profit Target by Number', 'Profit Target by Number'), ('Profit Target by Percentage', 'Profit Target by Percentage'), ('Weighted Profit by Number', 'Weighted Profit by Number'), ('Weighted Profit by Percentage', 'Weighted Profit by Percentage'), ('Transition Profit Tgt Percent', 'Transition Profit Tgt Percent'), ('Completion Profit Tgt Percent', 'Completion Profit Tgt Percent')], default='Stock Price by Number', max_length=50)),
                ('acquisition_price_factor', models.CharField(choices=[('Bull', 'Bull'), ('Bear', 'Bear'), ('Bull and Bear', 'Bull and Bear'), ('Bull or Bear', 'Bull or Bear')], default='Bull', max_length=25)),
                ('proximity_calculation_automatic', models.BooleanField(default=True)),
                ('bull_acquisition_volatility_factor', models.CharField(choices=[('.10', '.10'), ('.15', '.15'), ('.20', '.20'), ('.25', '.25'), ('.30', '.30')], default='.10', max_length=25)),
                ('bear_acquisition_volatility_factor', models.CharField(choices=[('.10', '.10'), ('.15', '.15'), ('.20', '.20'), ('.25', '.25'), ('.30', '.30')], default='.10', max_length=25)),
                ('acquisition_time_proximity', models.BooleanField(default=False)),
                ('min_time_between_purchases', models.CharField(choices=[('15', '15'), ('30', '30'), ('60', '60')], default='60', max_length=25)),
                ('and_or_1', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='OR', max_length=10)),
                ('acquisition_volume_proximity', models.BooleanField(default=False)),
                ('min_volume_between_purchases', models.CharField(choices=[('15M', '15M'), ('30M', '30M'), ('60M', '60M')], default='15M', max_length=25)),
                ('volume_fraction_to_average', models.IntegerField(blank=True, default=1)),
                ('and_or_2', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='OR', max_length=10)),
                ('simultaneous_bull_bear_acquisitions', models.BooleanField(default=True)),
                ('time_difference_between_acquisitions', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=25)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modify_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date modified')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.equitystrategy')),
            ],
        ),
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bullbearetfs.equitystrategy'),
        ),
    ]
