# Generated by Django 3.1.3 on 2020-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0010_auto_20201113_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='etfandreversepairrobot',
            name='version',
            field=models.CharField(choices=[('1.0.0', '1.0.0'), ('2.0.0', '2.0.0')], default='1.0.0', max_length=10),
        ),
    ]
