# Generated by Django 3.1.3 on 2020-11-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0015_auto_20201113_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfpairrobotexecutiondata',
            name='order_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
