# Generated by Django 3.1.3 on 2020-12-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0018_auto_20201215_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfpairrobotexecutiondata',
            name='order_client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
