# Generated by Django 3.1.3 on 2020-12-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0019_auto_20201215_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfpairrobotexecutiondata',
            name='exec_params',
            field=models.CharField(blank=True, default='', max_length=900),
        ),
    ]
