# Generated by Django 3.1.3 on 2020-12-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullbearetfs', '0022_auto_20201215_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfpairrobotexecutiondata',
            name='exec_params',
            field=models.CharField(blank=True, default='', max_length=3500),
        ),
    ]
